version: '2'

services:
### Workspace Utilities Container ###########################
    workspace:
        container_name: ir-workspace
        hostname: ir-workspace
        build:
            dockerfile: ./docker/workspace/Dockerfile
            context: ./
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "80:8080"
        restart: always
        networks:
          - esnet

### MySQL Container #############################
    mysql:
        container_name: ir-mysql
        hostname: mysql
        build:
          dockerfile: ./docker/mysql/Dockerfile
          context: ./
        restart: always
        env_file:
          - ./docker/development.env
        volumes:
          - mysql-data:/var/lib/mysql
        networks:
          - esnet

### Adminer Container ###########################
    adminer:
        container_name: ir-adminer
        hostname: adminer
        build:
          dockerfile: ./docker/adminer/Dockerfile
          context: ./
        ports:
          - "8083:8080"
        restart: always
        networks:
            - esnet

volumes:
  mysql-data:

networks:
  esnet:

